# Generated by Django 3.0.2 on 2020-01-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facelogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp',
            field=models.ImageField(blank=True, upload_to='login'),
        ),
        migrations.DeleteModel(
            name='Snaps',
        ),
    ]
