# Generated by Django 3.0.2 on 2020-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facelogin', '0002_auto_20200118_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='temp',
            field=models.ImageField(default='default.png', upload_to='login'),
        ),
    ]
